### ISSUE TITLE
campus manual migrations

### ISSUE THREAD

**Issue by evanwill** [uidaholib/campus-collections-template#1]
- [x] U of I Commencement Programs
- [x] Here We Have Idaho
- [x] U of I Women's Center Collection
- [x] Vandal Video Collection (these are all YouTube items not currently using. metadata should be QC-ed to figure out if there is something jumbled)

[migration outline](https://github.com/uidaholib/cdm-migration-project-docs/blob/main/manual-migrate.md)

**Comment by aweymo-ui** [comment]
Notes:
- I worked on the Women's Center and Vandal Video collections
- Opted for the light background of the new template for the subject clouds in both instead of adjusting back to the black background and blue print for better accessibility
- Adjusted the minimum number of subjects in the Women's Center and zoomed in on the map since the footprint is pretty tiny
- Checked in with Kevin about the Video Vandal collection and it sounds like we didn't have a lot of context when we received the digitized material. I QC'd the metadata and, though lacking descriptive material, all seems accurate.

**Comment by evanwill** [comment]
@aweymo-ui  on Vandal Video, the featured-image is a link to CONTENTdm image. I would download that, crop it to a landscape size that works for the banner (i.e right now it is a [big portrait orientation item](https://cdm17254.contentdm.oclc.org/digital/iiif/football/19/full/max/0/default.jpg), we don't need it that tall, so crop down to an area of interest that works for the banner) , and add to the objects folder and use a link to there.

**Comment by aweymo-ui** [comment]
I cropped the image, added to objects and updated the theme.yml with a path to https://www.lib.uidaho.edu/digital/objects/vandal_video_banner.jpg

**Comment by kxuidaho** [comment]
All 4 collections are updated and live w/ the new template!
